APP_VERSION = "1.6.0"
BASE_URL = "https://president-trading-system-1.onrender.com"

REFRESH_EVERY_SECONDS = 180  # 3분
STALE_AFTER_SECONDS = 420    # 7분
STARTUP_WARMUP = True

# 모집단은 넓게, stage2만 제한
MAIN_CANDIDATE_POOL = 220
SUB_CANDIDATE_POOL = 320
MAIN_STAGE2_MAX = 40
SUB_STAGE2_MAX = 70

OHLCV_LIMIT_1H = 160
OHLCV_LIMIT_30M = 160
OHLCV_LIMIT_4H = 120

MIN_QUOTE_VOLUME_MAIN = 8_000_000
MIN_QUOTE_VOLUME_SUB = 3_000_000

EXCLUDED_SUFFIXES = ("UP/USDT", "DOWN/USDT", "BULL/USDT", "BEAR/USDT")
EXCLUDED_EXACT = {
    "USDC/USDT", "FDUSD/USDT", "TUSD/USDT", "USDP/USDT", "DAI/USDT",
    "USDS/USDT", "EUR/USDT", "PAXG/USDT"
}
