APP_VERSION = "2.0.4-upbit-stable"
BASE_URL = "https://president-trading-system-1.onrender.com"
MARKET = "UPBIT_KRW"

# Upbit KRW 마켓 기준. 코인 수가 Binance USDT보다 적으므로 풀을 현실적으로 재조정
UNIVERSE_TOP_N_MAIN = 70
UNIVERSE_TOP_N_SUB = 90
STAGE1_MAX_MAIN = 42
STAGE1_MAX_SUB = 55
STAGE2_MAX_MAIN = 12
STAGE2_MAX_SUB = 16

REFRESH_INTERVAL_MAIN = 180
REFRESH_INTERVAL_SUB = 300

# 24시간 거래대금 하한(원)
MIN_QUOTE_VOLUME_KRW = 3_000_000_000

REFRESHING_MESSAGE = "초기 스캔 또는 백그라운드 갱신 중입니다."

# PDF 정합형 파라미터
# 1시간봉 중심 + 3포인트 다이버전스 연계 + 0.618~0.786 되돌림 + 피보나치 1 이탈 무효
PIVOT_LOOKBACK = 2
PIVOT_MIN_GAP = 5
PIVOT_MAX_GAP = 72
MIN_THREE_POINT_SPAN = 12
MAX_SECOND_LOW_UNDERCUT_PCT = 6.0
MIN_RSI_DIVERGENCE_GAP = 8.0
MAX_BOUNCE_FROM_LOW_PCT = 11.5
RSI_OVERSOLD_MAX = 31.5
RSI_DEEP_OVERSOLD_MAX = 28.0
ATR_PERIOD = 14
ATR_STOP_BUFFER = 0.20
MAIN_MIN_RR = 1.35
SUB_MIN_RR = 1.0
VOLUME_SURGE_MULTIPLIER = 1.25
MICRO_BREAKOUT_LOOKBACK = 5
MICRO_BREAKOUT_LOOKBACK_15M = 8
CRASH_FILTER_20BAR_PCT = -25.0
RECENT_SWING_LOOKBACK = 72
FIB_TOLERANCE = 0.016
FIB_MIN_MOVE_PCT = 4.0
STOP_BUFFER_PCT = 0.35

UNIVERSE_CACHE_TTL_SEC = 90
OHLCV_CACHE_TTL_SEC = 90

STAGE1_WORKERS = 2
STAGE2_WORKERS = 2
MIN_MAIN_CONFIRMATIONS = 2
MIN_SUB_CONFIRMATIONS = 1

API_MIN_INTERVAL_SEC = 0.18
API_RETRY_MAX = 4
API_BACKOFF_BASE_SEC = 0.6
