APP_VERSION = "2.0.0-upbit"
BASE_URL = "https://president-trading-system-1.onrender.com"
MARKET = "UPBIT_KRW"

# Upbit KRW 마켓 기준. 코인 수가 Binance USDT보다 적으므로 풀을 현실적으로 재조정
UNIVERSE_TOP_N_MAIN = 90
UNIVERSE_TOP_N_SUB = 130
STAGE1_MAX_MAIN = 70
STAGE1_MAX_SUB = 100
STAGE2_MAX_MAIN = 24
STAGE2_MAX_SUB = 48

REFRESH_INTERVAL_MAIN = 180
REFRESH_INTERVAL_SUB = 300

# 24시간 거래대금 하한(원)
MIN_QUOTE_VOLUME_KRW = 3_000_000_000

REFRESHING_MESSAGE = "초기 스캔 또는 백그라운드 갱신 중입니다."

# PDF 정합형 파라미터
# 1시간봉 중심 + 3포인트 다이버전스 연계 + 0.618~0.786 되돌림 + 피보나치 1 이탈 무효
PIVOT_LOOKBACK = 2
PIVOT_MIN_GAP = 5
PIVOT_MAX_GAP = 72
MIN_THREE_POINT_SPAN = 12
MAX_SECOND_LOW_UNDERCUT_PCT = 6.0
MIN_RSI_DIVERGENCE_GAP = 8.0
MAX_BOUNCE_FROM_LOW_PCT = 10.0
RSI_OVERSOLD_MAX = 30.0
RSI_DEEP_OVERSOLD_MAX = 28.0
ATR_PERIOD = 14
ATR_STOP_BUFFER = 0.20
MAIN_MIN_RR = 1.5
SUB_MIN_RR = 1.0
VOLUME_SURGE_MULTIPLIER = 1.25
MICRO_BREAKOUT_LOOKBACK = 5
MICRO_BREAKOUT_LOOKBACK_15M = 8
CRASH_FILTER_20BAR_PCT = -25.0
RECENT_SWING_LOOKBACK = 72
FIB_TOLERANCE = 0.012
FIB_MIN_MOVE_PCT = 4.0
STOP_BUFFER_PCT = 0.35
